/* ==========================================================================
   INTELLOOP — EXPORT HELPERS (Markdown, JSON, CSV, Printable)
   ========================================================================== */

export function downloadFile(content, filename, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportMissionAsMarkdown(mission) {
  if (!mission) return;
  const content = `# INTELLOOP INTELLIGENCE BRIEFING
**Mission ID:** ${mission.id}  
**Objective:** ${mission.title}  
**Assigned Agent:** ${mission.agentName || 'Sentinel-Prime'}  
**Status:** ${mission.status}  
**Completed At:** ${mission.completedAt || new Date().toISOString()}  
**Execution Latency:** ${(mission.executionTimeMs / 1000).toFixed(2)}s  
**Total Steps:** ${mission.steps?.length || 0}  
**Tools Invoked:** ${mission.toolsUsed?.join(', ') || 'None'}  

---

## Executive Summary & Briefing
${mission.finalResult || 'No briefing content available.'}

---

## Execution Step History
${(mission.steps || [])
  .map(
    (step, idx) =>
      `### Step ${idx + 1}: ${step.title || step.type}
- **Type:** ${step.type}
- **Timestamp:** ${step.timestamp}
- **Summary:** ${step.summary || ''}
${step.toolName ? `- **Tool:** \`${step.toolName}\` (Input: \`${JSON.stringify(step.toolInput || {})}\`)` : ''}
${step.observation ? `- **Observation:** ${step.observation}` : ''}`
  )
  .join('\n\n')}

---
*Generated by Intelloop AI Intelligence Platform*
`;

  downloadFile(content, `Intelloop-Briefing-${mission.id}.md`, 'text/markdown');
}

export function exportMissionAsJson(mission) {
  if (!mission) return;
  const content = JSON.stringify(mission, null, 2);
  downloadFile(content, `Intelloop-Mission-${mission.id}.json`, 'application/json');
}

export function exportLogsAsCsv(logs = []) {
  const headers = ['Timestamp', 'Mission ID', 'Agent', 'Event Type', 'Tool', 'Summary', 'Duration (ms)'];
  const rows = logs.map(l => [
    `"${l.timestamp || ''}"`,
    `"${l.missionId || ''}"`,
    `"${l.agentName || ''}"`,
    `"${l.type || ''}"`,
    `"${l.toolName || ''}"`,
    `"${(l.summary || '').replace(/"/g, '""')}"`,
    `"${l.durationMs || 0}"`
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  downloadFile(csv, `Intelloop-Activity-Logs-${Date.now()}.csv`, 'text/csv');
}

export function copyToClipboard(text) {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text);
  }
  // Fallback for older browsers
  const textArea = document.createElement('textarea');
  textArea.value = text;
  textArea.style.position = 'fixed';
  textArea.style.left = '-999999px';
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  try {
    document.execCommand('copy');
  } catch (err) {
    console.error('Copy failed', err);
  }
  document.body.removeChild(textArea);
  return Promise.resolve();
}
